apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kalimba-client.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kalimba-client.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kalimba-client.fullname" . }}
    spec:
      containers:
        - name: kalimba-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
